### ISSUE TITLE
Error: 'target' option must be one of

### ISSUE THREAD

**Issue by TAnas0** [christophehurpeau/babel-preset-latest-node#60]
Hey @christophehurpeau,

Thanks for the project. Just helped me setup cleanly my Babel 7 configuration for a NodeJS script, after many hours wasted in scattered tutorials, SO threads and Github issues.

Hope this gains as much traction, or more than your other Babel plugin.

As to my issue, I faced an error message trying to launch the Babel build when the `target` option was not specified, in both the CLI and using the `.babelrc`.

Your Readme suggests that the `target` configuration is optional but I am facing an error:

```bash
Error: [BABEL] /home/********************/script.js: Preset latest-node 'target' option must one of 6, 6.5, 8, 8.3, 10, 10.13, 11, current
```

Cheers

**Comment by christophehurpeau** [comment]
Hello @TAnas0 ! Thank you for your support :)

Indeed it was not optional, I fixed that in the [v3.1.1](https://github.com/christophehurpeau/babel-preset-latest-node/blob/master/CHANGELOG.md#311-2019-03-12) and added a test 

Thank you :)
